#pragma once
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_ttf.h>
#include <stdio.h>
#include <string>
#include <memory>
#include <unordered_map>
#include <queue>
#include <vector>
#include <set>
#include <unordered_set>
#include <functional>
#include <map>
#include <typeinfo>
#include <typeindex>
#include <tuple>

#include "Transform.h"
